# Generated by Django 4.2.4 on 2023-08-30 08:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(default='US', max_length=255, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default=uuid.uuid4, max_length=255, verbose_name='SKU'),
        ),
    ]
