# Generated by Django 4.2.4 on 2023-08-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0004_client_country_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='Medium', max_length=100, verbose_name='Product Category'),
        ),
    ]
