# Generated by Django 6.0.3 on 2026-04-23 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0006_productcategory_remove_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Month')),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Sales')),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_app.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Monthly Sales Summary',
                'verbose_name_plural': 'Monthly Sales Summaries',
                'unique_together': {('product', 'month')},
            },
        ),
        migrations.RunSQL("""
        CREATE TABLE regional_sales_summary (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    product_name VARCHAR(100) NOT NULL,
                    country VARCHAR(100) NOT NULL,
                    total_sales DECIMAL(12, 2) NOT NULL DEFAULT 0,
                    total_quantity DECIMAL(12, 2) NOT NULL DEFAULT 0
        """)
    ]
