repos:

-   repo: https://github.com/adamchainz/blacken-docs
    rev: ""
    hooks:
    -   id: blacken-docs
        additional_dependencies:
        - black==22.12.0

-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.9