repos:

-   repo: https://github.com/adamchainz/blacken-docs
    rev: "1.13.0"
    hooks:
    -   id: blacken-docs
        additional_dependencies:
        - black==22.12.0

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
      language_version: python3.9

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.0.287
  hooks:
    - id: ruff
